import type { MasterDefinition, MasterRecord } from "./types";
import { createMasterRows } from "./utils";

const asDate = (value: string) => new Date(value);

function withAuditFields<T extends MasterRecord>(rows: ReadonlyArray<T>) {
  return rows.map((row) => ({
    ...row,
    createdBy: String(row.createdBy ?? row.createdEditedBy ?? ""),
    editedBy: String(row.editedBy ?? row.updatedBy ?? row.createdEditedBy ?? ""),
    createdDate:
      (row.createdDate ??
        row.createdEditedDate ??
        row.createdEditedAt ??
        null) as MasterRecord[string],
    updatedDate:
      (row.updatedDate ??
        row.updatedAt ??
        row.createdEditedDate ??
        row.createdEditedAt ??
        null) as MasterRecord[string],
  }));
}

const itemRows = withAuditFields(createMasterRows("item-master", [
  {
    itemName: "Oak Quarter Cut Veneer",
    itemCode: "ITM-OAK-001",
    category: "Decorative Veneer",
    subCategory: "Natural Veneer",
    color: "Natural Oak",
    gst: "12%",
    hsn: "4408",
    remark: "Standard oak veneer catalog item.",
    createdEditedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-05-10"),
  },
  {
    itemName: "Walnut Crown Cut Veneer",
    itemCode: "ITM-WAL-014",
    category: "Decorative Veneer",
    subCategory: "Dyed Veneer",
    color: "Classic Walnut",
    gst: "12%",
    hsn: "4408",
    remark: "Premium walnut veneer for interior applications.",
    createdEditedBy: "Neha Shah",
    createdEditedDate: asDate("2026-05-16"),
  },
  {
    itemName: "Teak Architectural Sheet",
    itemCode: "ITM-TEK-021",
    category: "Engineered Panel",
    subCategory: "Architectural Panel",
    color: "Golden Teak",
    gst: "18%",
    hsn: "4412",
    remark: "Architectural teak sheet for premium paneling.",
    createdEditedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-05-22"),
  },
  {
    itemName: "Ash Rift Cut Panel",
    itemCode: "ITM-ASH-032",
    category: "Engineered Panel",
    subCategory: "Structural Panel",
    color: "Soft Ash",
    gst: "18%",
    hsn: "4411",
    remark: "Ash panel aligned to rift-cut project demand.",
    createdEditedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-06-03"),
  },
  {
    itemName: "Calibrated Board 18mm",
    itemCode: "ITM-PLY-044",
    category: "Plywood",
    subCategory: "Calibrated Board",
    color: "Natural Oak",
    gst: "18%",
    hsn: "4412",
    remark: "Calibrated plywood board for CNC-ready production.",
    createdEditedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-06-10"),
  },
  {
    itemName: "Prelam MDF Walnut",
    itemCode: "ITM-MDF-058",
    category: "MDF",
    subCategory: "Prelam Board",
    color: "Classic Walnut",
    gst: "18%",
    hsn: "4411",
    remark: "Pre-laminated MDF for wardrobe and panel finish work.",
    createdEditedBy: "Neha Shah",
    createdEditedDate: asDate("2026-06-18"),
  },
]));

const itemCategoryRows = withAuditFields(createMasterRows("item-category-master", [
  {
    categoryName: "Decorative Veneer",
    remark: "Interior decorative veneer category.",
    createdEditedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-04-18"),
  },
  {
    categoryName: "Engineered Panel",
    remark: "Structured panels for architectural applications.",
    createdEditedBy: "Neha Shah",
    createdEditedDate: asDate("2026-05-02"),
  },
  {
    categoryName: "Plywood",
    remark: "Structural board stock for standard production runs.",
    createdEditedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-05-15"),
  },
  {
    categoryName: "MDF",
    remark: "Composite board category for modular fabrication.",
    createdEditedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-06-01"),
  },
]));

const itemSubCategoryRows = withAuditFields(createMasterRows("item-sub-category-master", [
  {
    itemSubCategory: "Natural Veneer",
    category: "Decorative Veneer",
    createdEditedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-04-20"),
  },
  {
    itemSubCategory: "Dyed Veneer",
    category: "Decorative Veneer",
    createdEditedBy: "Neha Shah",
    createdEditedDate: asDate("2026-05-08"),
  },
  {
    itemSubCategory: "Architectural Panel",
    category: "Engineered Panel",
    createdEditedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-05-19"),
  },
  {
    itemSubCategory: "Structural Panel",
    category: "Engineered Panel",
    createdEditedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-06-02"),
  },
  {
    itemSubCategory: "Calibrated Board",
    category: "Plywood",
    createdEditedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-06-11"),
  },
  {
    itemSubCategory: "Prelam Board",
    category: "MDF",
    createdEditedBy: "Neha Shah",
    createdEditedDate: asDate("2026-06-18"),
  },
]));

const colorRows = withAuditFields(createMasterRows("color-master", [
  {
    colorName: "Natural Oak",
    status: "Active",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Neha Shah",
    createdEditedDate: asDate("2026-04-14"),
    updatedDate: asDate("2026-05-02"),
  },
  {
    colorName: "Classic Walnut",
    status: "Active",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-04-20"),
    updatedDate: asDate("2026-05-11"),
  },
  {
    colorName: "Golden Teak",
    status: "Active",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-05-06"),
    updatedDate: asDate("2026-05-26"),
  },
  {
    colorName: "Soft Ash",
    status: "Inactive",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-05-18"),
    updatedDate: asDate("2026-06-04"),
  },
]));

const cutRows = withAuditFields(createMasterRows("cut-master", [
  {
    cutName: "Quarter Cut",
    remark: "Used for linear veneer grain selection.",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Neha Shah",
    createdEditedDate: asDate("2026-04-16"),
    updatedDate: asDate("2026-05-06"),
  },
  {
    cutName: "Crown Cut",
    remark: "Preferred for broad cathedral grain patterns.",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-04-29"),
    updatedDate: asDate("2026-05-18"),
  },
  {
    cutName: "Rift Cut",
    remark: "Used where consistent straight grain is required.",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-05-12"),
    updatedDate: asDate("2026-05-31"),
  },
  {
    cutName: "Rotary Cut",
    remark: "Bulk inward cut option for production stock.",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-05-25"),
    updatedDate: asDate("2026-06-07"),
  },
]));

const customerRows = withAuditFields(createMasterRows("customer-master", [
  {
    customerName: "Vikram Mehta",
    companyName: "Prime Habitat Studio",
    customerType: "Architect",
    dob: asDate("1986-03-12"),
    email: "vikram@primehabitat.in",
    phoneNumber: "+91 98765 44120",
    gstNo: "27AABCP1122L1ZX",
    gstUpload: "prime-habitat-gst.pdf",
    panNo: "AABCP1122L",
    panUpload: "prime-habitat-pan.pdf",
    remark: "Premium interior fit-out account.",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-04-22"),
    updatedDate: asDate("2026-05-28"),
  },
  {
    customerName: "Aarav Soni",
    companyName: "Timberline Projects",
    customerType: "Dealer",
    dob: asDate("1989-07-08"),
    email: "aarav@timberline.in",
    phoneNumber: "+91 98250 77891",
    gstNo: "29AACCT4488C1ZP",
    gstUpload: "timberline-gst.pdf",
    panNo: "AACCT4488C",
    panUpload: "timberline-pan.pdf",
    remark: "Bulk plywood and veneer dispatch account.",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-05-03"),
    updatedDate: asDate("2026-06-01"),
  },
  {
    customerName: "Rhea Kapoor",
    companyName: "Aura Living Concepts",
    customerType: "Retail",
    dob: asDate("1992-11-16"),
    email: "rhea@auraliving.in",
    phoneNumber: "+91 98111 23498",
    gstNo: "24AATCA5567D1Z2",
    gstUpload: "aura-living-gst.pdf",
    panNo: "AATCA5567D",
    panUpload: "aura-living-pan.pdf",
    remark: "Focus on designer sample sheets.",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Neha Shah",
    createdEditedDate: asDate("2026-05-17"),
    updatedDate: asDate("2026-06-05"),
  },
  {
    customerName: "Harsh Vora",
    companyName: "Woodform Spaces",
    customerType: "Architect",
    dob: asDate("1984-01-29"),
    email: "harsh@woodformspaces.com",
    phoneNumber: "+91 98989 67012",
    gstNo: "07AAFCW9011J1ZW",
    gstUpload: "woodform-gst.pdf",
    panNo: "AAFCW9011J",
    panUpload: "woodform-pan.pdf",
    remark: "Requires FSC-certified veneer selections.",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-03-28"),
    updatedDate: asDate("2026-05-19"),
  },
]));

const unitRows = withAuditFields(createMasterRows("unit-master", [
  {
    unitName: "Square Meter",
    symbolicName: "SQM",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Neha Shah",
    status: "Active",
    createdEditedDate: asDate("2026-04-11"),
    updatedDate: asDate("2026-05-04"),
  },
  {
    unitName: "Sheet",
    symbolicName: "SHT",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    status: "Active",
    createdEditedDate: asDate("2026-04-19"),
    updatedDate: asDate("2026-05-12"),
  },
  {
    unitName: "Bundle",
    symbolicName: "BDL",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    status: "Active",
    createdEditedDate: asDate("2026-05-07"),
    updatedDate: asDate("2026-05-21"),
  },
  {
    unitName: "Piece",
    symbolicName: "PCS",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Atharva Patil",
    status: "Inactive",
    createdEditedDate: asDate("2026-05-24"),
    updatedDate: asDate("2026-06-06"),
  },
]));

const supplierRows = withAuditFields(createMasterRows("supplier-master", [
  {
    supplierName: "Arihant Veneers LLP",
    supplierType: "Domestic",
    contactPersonName: "Karan Shah",
    designation: "Sales Manager",
    mobileNumber: "+91 98250 11223",
    emailAddress: "karan@arihantveneers.in",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    msmeType: "Small",
    msmeNo: "UDYAM-GJ-10-1122334",
    gstNo: "24AAWFA2214F1Z5",
    gstUpload: "arihant-gst.pdf",
    panNo: "AAWFA2214F",
    panUpload: "arihant-pan.pdf",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Neha Shah",
    createdEditedDate: asDate("2026-04-12"),
    updatedDate: asDate("2026-05-07"),
  },
  {
    supplierName: "Baltic Timber Supply",
    supplierType: "Import",
    contactPersonName: "Elina Markova",
    designation: "Export Coordinator",
    mobileNumber: "+371 22 455 881",
    emailAddress: "elina@baltictimber.eu",
    city: "Riga",
    state: "Riga",
    country: "Latvia",
    msmeType: "Corporate",
    msmeNo: "EU-CORP-771092",
    gstNo: "LT-EXIM-771092",
    gstUpload: "baltic-gst.pdf",
    panNo: "BTSUP7710K",
    panUpload: "baltic-pan.pdf",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-04-27"),
    updatedDate: asDate("2026-05-20"),
  },
  {
    supplierName: "City Timber Traders",
    supplierType: "Domestic",
    contactPersonName: "Nitin Arora",
    designation: "Proprietor",
    mobileNumber: "+91 98101 44770",
    emailAddress: "nitin@citytimber.in",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    msmeType: "Medium",
    msmeNo: "UDYAM-DL-05-7784510",
    gstNo: "07AAKFC5561N1Z8",
    gstUpload: "city-timber-gst.pdf",
    panNo: "AAKFC5561N",
    panUpload: "city-timber-pan.pdf",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-05-10"),
    updatedDate: asDate("2026-05-29"),
  },
  {
    supplierName: "Nordic Veneer House",
    supplierType: "Import",
    contactPersonName: "Mikael Sorensen",
    designation: "Account Director",
    mobileNumber: "+45 31 77 9821",
    emailAddress: "mikael@nordicveneer.dk",
    city: "Aarhus",
    state: "Central Denmark",
    country: "Denmark",
    msmeType: "Corporate",
    msmeNo: "EU-CORP-883214",
    gstNo: "DK-EXIM-883214",
    gstUpload: "nordic-gst.pdf",
    panNo: "NVHOU8832Q",
    panUpload: "nordic-pan.pdf",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-05-24"),
    updatedDate: asDate("2026-06-08"),
  },
]));

const transporterRows = withAuditFields(createMasterRows("transporter-master", [
  {
    transporterName: "Amardeep Cargo Logistic",
    branchName: "Ahmedabad",
    transporterId: "TRN-AMD-001",
    type: "Road",
    areaOfOperation: "Gujarat",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Neha Shah",
    createdEditedDate: asDate("2026-05-04"),
    updatedDate: asDate("2026-06-02"),
  },
  {
    transporterName: "National Freight Carrier",
    branchName: "Mumbai",
    transporterId: "TRN-NFC-014",
    type: "Road",
    areaOfOperation: "West India",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-05-12"),
    updatedDate: asDate("2026-06-08"),
  },
  {
    transporterName: "Deluxe Transport Services",
    branchName: "Surat",
    transporterId: "TRN-DTS-021",
    type: "Road",
    areaOfOperation: "Pan India",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-05-21"),
    updatedDate: asDate("2026-06-15"),
  },
  {
    transporterName: "Blue Sky Air Cargo",
    branchName: "Delhi",
    transporterId: "TRN-BSA-032",
    type: "Air",
    areaOfOperation: "North India",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-06-01"),
    updatedDate: asDate("2026-06-20"),
  },
]));

const gstRows = withAuditFields(createMasterRows("gst-master", [
  {
    gstPercentage: "5%",
    remark: "Raw material and accessory inward",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Neha Shah",
    status: "Active",
    createdEditedAt: asDate("2026-04-10"),
    updatedAt: asDate("2026-05-03"),
  },
  {
    gstPercentage: "12%",
    remark: "Decorative sheet and retail panel sales",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    status: "Active",
    createdEditedAt: asDate("2026-04-18"),
    updatedAt: asDate("2026-05-14"),
  },
  {
    gstPercentage: "18%",
    remark: "Premium veneer and architectural panel billing",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    status: "Active",
    createdEditedAt: asDate("2026-05-05"),
    updatedAt: asDate("2026-05-26"),
  },
  {
    gstPercentage: "28%",
    remark: "Restricted category kept for legacy mapping only",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Atharva Patil",
    status: "Inactive",
    createdEditedAt: asDate("2026-05-19"),
    updatedAt: asDate("2026-06-07"),
  },
]));

const hsnRows = withAuditFields(createMasterRows("hsn-master", [
  {
    hsnCode: "4408",
    hsnCodeDescription: "Sheets for veneering, sliced",
    gstPercentage: "12%",
    status: "Active",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Neha Shah",
    createdEditedDate: asDate("2026-04-09"),
    updatedDate: asDate("2026-05-01"),
  },
  {
    hsnCode: "4412",
    hsnCodeDescription: "Plywood, veneered panels",
    gstPercentage: "18%",
    status: "Active",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-04-21"),
    updatedDate: asDate("2026-05-16"),
  },
  {
    hsnCode: "4411",
    hsnCodeDescription: "Fibreboard of wood",
    gstPercentage: "18%",
    status: "Active",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-05-12"),
    updatedDate: asDate("2026-05-30"),
  },
  {
    hsnCode: "4421",
    hsnCodeDescription: "Other articles of wood",
    gstPercentage: "28%",
    status: "Inactive",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-05-25"),
    updatedDate: asDate("2026-06-08"),
  },
]));

const warehouseRows = withAuditFields(createMasterRows("warehouse-location-master", [
  {
    warehouseName: "Warehouse A",
    warehouseCode: "WH-A-01",
    warehouseType: "Inward",
    status: "Active",
    address: "Plot 18, GIDC Estate, Changodar",
    city: "Ahmedabad",
    pincode: "382213",
    state: "Gujarat",
    country: "India",
    remark: "Primary inward warehouse for veneer receipts.",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Neha Shah",
    createdEditedDate: asDate("2026-04-13"),
    updatedDate: asDate("2026-05-05"),
  },
  {
    warehouseName: "Warehouse B",
    warehouseCode: "WH-B-02",
    warehouseType: "Storage",
    status: "Active",
    address: "Shed 9, Timber Market Road, Narol",
    city: "Ahmedabad",
    pincode: "382405",
    state: "Gujarat",
    country: "India",
    remark: "Finished inspected stock storage location.",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-04-26"),
    updatedDate: asDate("2026-05-18"),
  },
  {
    warehouseName: "Warehouse C",
    warehouseCode: "WH-C-03",
    warehouseType: "Production",
    status: "Active",
    address: "Unit 4, Industrial Layout, Sanand",
    city: "Sanand",
    pincode: "382110",
    state: "Gujarat",
    country: "India",
    remark: "Production stage transfer warehouse.",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-05-09"),
    updatedDate: asDate("2026-05-28"),
  },
  {
    warehouseName: "Sample Store",
    warehouseCode: "WH-S-04",
    warehouseType: "Storage",
    status: "Inactive",
    address: "Office Basement, Iscon Cross Road",
    city: "Ahmedabad",
    pincode: "380015",
    state: "Gujarat",
    country: "India",
    remark: "Reserved storage for archived and sample lots.",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-05-23"),
    updatedDate: asDate("2026-06-06"),
  },
]));

const currencyRows = withAuditFields(createMasterRows("currency-master", [
  {
    currencyName: "Indian Rupee",
    remark: "Default local transaction currency",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Neha Shah",
    status: "Active",
    createdEditedAt: asDate("2026-04-08"),
    updatedAt: asDate("2026-05-02"),
  },
  {
    currencyName: "US Dollar",
    remark: "Used for veneer import billing",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    status: "Active",
    createdEditedAt: asDate("2026-04-19"),
    updatedAt: asDate("2026-05-11"),
  },
  {
    currencyName: "Euro",
    remark: "Used for European supplier settlements",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    status: "Active",
    createdEditedAt: asDate("2026-05-03"),
    updatedAt: asDate("2026-05-24"),
  },
  {
    currencyName: "Pound Sterling",
    remark: "Reserved for legacy procurement mapping",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Atharva Patil",
    status: "Inactive",
    createdEditedAt: asDate("2026-05-17"),
    updatedAt: asDate("2026-06-04"),
  },
]));

const consumablesRows = withAuditFields(createMasterRows("consumables-master", [
  {
    consumableName: "Fevicol SH Resin",
    category: "Adhesive",
    unitName: "Kilogram",
    gst: "18%",
    hsn: "3506",
    remark: "Primary resin used for veneer bonding and panel lamination.",
    createdEditedBy: "Atharva Patil",
    updatedBy: "Neha Shah",
    createdEditedDate: asDate("2026-05-08"),
    updatedDate: asDate("2026-06-02"),
  },
  {
    consumableName: "Melamine Glue Hardener",
    category: "Chemical",
    unitName: "Litre",
    gst: "18%",
    hsn: "3815",
    remark: "Used with hot press adhesive mixes for structural bonding.",
    createdEditedBy: "Neha Shah",
    updatedBy: "Rohit Jain",
    createdEditedDate: asDate("2026-05-16"),
    updatedDate: asDate("2026-06-09"),
  },
  {
    consumableName: "Edge Protector Roll",
    category: "Packaging",
    unitName: "Roll",
    gst: "12%",
    hsn: "3923",
    remark: "Protective packing material for finished veneer bundles.",
    createdEditedBy: "Rohit Jain",
    updatedBy: "Aditi Desai",
    createdEditedDate: asDate("2026-05-28"),
    updatedDate: asDate("2026-06-14"),
  },
  {
    consumableName: "Sanding Belt 120 Grit",
    category: "Hardware",
    unitName: "Piece",
    gst: "18%",
    hsn: "6805",
    remark: "Standard sanding consumable for finishing and calibration runs.",
    createdEditedBy: "Aditi Desai",
    updatedBy: "Atharva Patil",
    createdEditedDate: asDate("2026-06-05"),
    updatedDate: asDate("2026-06-18"),
  },
]));

const uniqueOptions = (rows: ReadonlyArray<MasterRecord>, key: string) =>
  Array.from(
    new Set(rows.map((row) => String(row[key] ?? "")).filter(Boolean)),
  );

export const itemSubCategoryMasterOptions = uniqueOptions(
  itemSubCategoryRows,
  "itemSubCategory",
);

export const itemCategoryMasterOptions = uniqueOptions(
  itemCategoryRows,
  "categoryName",
);

export const itemMasterDefinition: MasterDefinition = {
  slug: "item-master",
  title: "Item Master",
  gridColumns: 4,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "itemName", label: "Item Name" },
    { key: "itemCode", label: "Item Code" },
    { key: "category", label: "Category" },
    { key: "subCategory", label: "Sub Category" },
    { key: "remark", label: "Remark" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "category", label: "Category", options: itemCategoryMasterOptions },
    { key: "subCategory", label: "Sub Category", options: itemSubCategoryMasterOptions },
  ],
  fields: [
    { key: "itemName", label: "Item Name", type: "text" },
    { key: "itemCode", label: "Item Code", type: "text" },
    { key: "category", label: "Category", type: "select", options: itemCategoryMasterOptions },
    { key: "subCategory", label: "Sub Category", type: "select", options: itemSubCategoryMasterOptions },
    { key: "color", label: "Color", type: "select", options: uniqueOptions(colorRows, "colorName") },
    { key: "gst", label: "GST", type: "select", options: uniqueOptions(gstRows, "gstPercentage") },
    { key: "hsn", label: "HSN", type: "select", options: uniqueOptions(hsnRows, "hsnCode") },
    { key: "remark", label: "Remark", type: "text" },
  ],
  rows: itemRows,
};

export const itemCategoryMasterDefinition: MasterDefinition = {
  slug: "item-category-master",
  title: "Item Category Master",
  gridColumns: 3,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "categoryName", label: "Category Name" },
    { key: "remark", label: "Remark" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "categoryName", label: "Category Name", options: uniqueOptions(itemCategoryRows, "categoryName") },
  ],
  fields: [
    { key: "categoryName", label: "Category Name", type: "text" },
    { key: "remark", label: "Remark", type: "text" },
  ],
  rows: itemCategoryRows,
};

export const itemSubCategoryMasterDefinition: MasterDefinition = {
  slug: "item-sub-category-master",
  title: "Item Sub-Category Master",
  gridColumns: 3,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "itemSubCategory", label: "Item Sub Category" },
    { key: "category", label: "Category" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "category", label: "Category", options: uniqueOptions(itemSubCategoryRows, "category") },
  ],
  fields: [
    { key: "itemSubCategory", label: "Item Sub Category", type: "text" },
    { key: "category", label: "Category", type: "select", options: uniqueOptions(itemCategoryRows, "categoryName") },
  ],
  rows: itemSubCategoryRows,
};

export const colorMasterDefinition: MasterDefinition = {
  slug: "color-master",
  title: "Color Master",
  gridColumns: 3,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "colorName", label: "Color name" },
    { key: "status", label: "Status" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "status", label: "Status", options: uniqueOptions(colorRows, "status") },
    { key: "createdBy", label: "Created By", options: uniqueOptions(colorRows, "createdBy") },
    { key: "editedBy", label: "Edited By", options: uniqueOptions(colorRows, "editedBy") },
  ],
  fields: [
    { key: "colorName", label: "Color Name", type: "text" },
    { key: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
  ],
  rows: colorRows,
};

export const cutMasterOptions = uniqueOptions(cutRows, "cutName");
export const gstMasterOptions = uniqueOptions(gstRows, "gstPercentage");

export const cutMasterDefinition: MasterDefinition = {
  slug: "cut-master",
  title: "Cut Master",
  gridColumns: 3,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "cutName", label: "Cut Name" },
    { key: "remark", label: "Remark" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "cutName", label: "Cut Name", options: cutMasterOptions },
  ],
  fields: [
    { key: "cutName", label: "Cut Name", type: "text" },
    { key: "remark", label: "Remark", type: "text" },
  ],
  rows: cutRows,
};

export const customerMasterDefinition: MasterDefinition = {
  slug: "customer-master",
  title: "Customer Master",
  gridColumns: 4,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "customerName", label: "Customer Name" },
    { key: "companyName", label: "Company Name" },
    { key: "customerType", label: "Customer Type" },
    { key: "dob", label: "Date of Birth" },
    { key: "email", label: "Email" },
    { key: "phoneNumber", label: "Phone Number" },
    { key: "gstNo", label: "GST" },
    { key: "gstUpload", label: "GST Upload" },
    { key: "panNo", label: "PAN No" },
    { key: "panUpload", label: "PAN Upload" },
    { key: "remark", label: "Remark" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "customerType", label: "Customer Type", options: uniqueOptions(customerRows, "customerType") },
    { key: "companyName", label: "Company Name", options: uniqueOptions(customerRows, "companyName") },
  ],
  fields: [
    { key: "customerName", label: "Customer Name", type: "text" },
    { key: "companyName", label: "Company Name", type: "text" },
    { key: "customerType", label: "Customer Type", type: "select", options: uniqueOptions(customerRows, "customerType") },
    { key: "dob", label: "Date of Birth", type: "date" },
    { key: "email", label: "Email", type: "text" },
    { key: "phoneNumber", label: "Phone Number", type: "text" },
    { key: "gstNo", label: "GST", type: "text" },
    { key: "gstUpload", label: "GST Upload", type: "file" },
    { key: "panNo", label: "PAN No", type: "text" },
    { key: "panUpload", label: "PAN Upload", type: "file" },
    { key: "remark", label: "Remark", type: "text" },
  ],
  rows: customerRows,
};

export const unitMasterDefinition: MasterDefinition = {
  slug: "unit-master",
  title: "Unit Master",
  gridColumns: 3,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "unitName", label: "Unit Name" },
    { key: "symbolicName", label: "Symbolic Name" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "status", label: "Status" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "status", label: "Status", options: uniqueOptions(unitRows, "status") },
    { key: "createdBy", label: "Created By", options: uniqueOptions(unitRows, "createdBy") },
  ],
  fields: [
    { key: "unitName", label: "Unit Name", type: "text" },
    { key: "symbolicName", label: "Symbolic Name", type: "text" },
    { key: "status", label: "Status", type: "select", options: uniqueOptions(unitRows, "status") },
  ],
  rows: unitRows,
};

export const supplierMasterDefinition: MasterDefinition = {
  slug: "supplier-master",
  title: "Supplier Master",
  gridColumns: 4,
  columns: [
    { key: "supplierName", label: "Supplier Name" },
    { key: "supplierType", label: "Supplier Type" },
    { key: "contactPersonName", label: "Contact Person Name" },
    { key: "designation", label: "Designation" },
    { key: "mobileNumber", label: "Mobile Number" },
    { key: "emailAddress", label: "Email Address" },
    { key: "city", label: "City" },
    { key: "state", label: "State" },
    { key: "country", label: "Country" },
    { key: "msmeType", label: "MSME Type" },
    { key: "msmeNo", label: "MSME No" },
    { key: "gstNo", label: "GST" },
    { key: "panNo", label: "PAN No" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "supplierType", label: "Supplier Type", options: uniqueOptions(supplierRows, "supplierType") },
    { key: "country", label: "Country", options: uniqueOptions(supplierRows, "country") },
    { key: "msmeType", label: "MSME Type", options: uniqueOptions(supplierRows, "msmeType") },
  ],
  fields: [
    { key: "supplierName", label: "Supplier Name", type: "text" },
    { key: "supplierType", label: "Supplier Type", type: "select", options: uniqueOptions(supplierRows, "supplierType") },
    { key: "contactPersonName", label: "Contact Person Name", type: "text" },
    { key: "designation", label: "Designation", type: "text" },
    { key: "mobileNumber", label: "Mobile Number", type: "text" },
    { key: "emailAddress", label: "Email Address", type: "text" },
    { key: "city", label: "City", type: "text" },
    { key: "state", label: "State", type: "text" },
    { key: "country", label: "Country", type: "select", options: uniqueOptions(supplierRows, "country") },
    { key: "msmeType", label: "MSME Type", type: "select", options: uniqueOptions(supplierRows, "msmeType") },
    { key: "msmeNo", label: "MSME No", type: "text" },
    { key: "gstNo", label: "GST", type: "text" },
    { key: "gstUpload", label: "GST Upload", type: "file" },
    { key: "panNo", label: "PAN No", type: "text" },
    { key: "panUpload", label: "PAN Upload", type: "file" },
  ],
  rows: supplierRows,
};

export const gstMasterDefinition: MasterDefinition = {
  slug: "gst-master",
  title: "GST Master",
  gridColumns: 3,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "gstPercentage", label: "GST %" },
    { key: "remark", label: "Remark" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "status", label: "Status" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "gstPercentage", label: "GST %", options: uniqueOptions(gstRows, "gstPercentage") },
    { key: "status", label: "Status", options: uniqueOptions(gstRows, "status") },
    { key: "createdBy", label: "Created By", options: uniqueOptions(gstRows, "createdBy") },
  ],
  fields: [
    { key: "gstPercentage", label: "GST %", type: "text" },
    { key: "status", label: "Status", type: "select", options: uniqueOptions(gstRows, "status") },
    { key: "remark", label: "Remark", type: "text" },
  ],
  rows: gstRows,
};

export const hsnMasterDefinition: MasterDefinition = {
  slug: "hsn-master",
  title: "HSN Master",
  gridColumns: 4,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "hsnCode", label: "HSN Code" },
    { key: "hsnCodeDescription", label: "HSN Code Description" },
    { key: "gstPercentage", label: "GST%" },
    { key: "status", label: "Status" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "gstPercentage", label: "GST%", options: uniqueOptions(hsnRows, "gstPercentage") },
    { key: "status", label: "Status", options: uniqueOptions(hsnRows, "status") },
    { key: "createdBy", label: "Created By", options: uniqueOptions(hsnRows, "createdBy") },
  ],
  fields: [
    { key: "hsnCode", label: "HSN Code", type: "text" },
    { key: "hsnCodeDescription", label: "HSN Code Description", type: "text" },
    { key: "gstPercentage", label: "GST%", type: "select", options: uniqueOptions(hsnRows, "gstPercentage") },
    { key: "status", label: "Status", type: "select", options: uniqueOptions(hsnRows, "status") },
  ],
  rows: hsnRows,
};

export const warehouseLocationMasterDefinition: MasterDefinition = {
  slug: "warehouse-location-master",
  title: "Warehouse / Location Master",
  gridColumns: 4,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "warehouseName", label: "Warehouse Name" },
    { key: "warehouseCode", label: "Warehouse Code" },
    { key: "status", label: "Status" },
    { key: "address", label: "Address" },
    { key: "country", label: "Country" },
    { key: "city", label: "City" },
    { key: "state", label: "State" },
    { key: "pincode", label: "Pincode" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "country", label: "Country", options: uniqueOptions(warehouseRows, "country") },
    { key: "state", label: "State", options: uniqueOptions(warehouseRows, "state") },
    { key: "status", label: "Status", options: uniqueOptions(warehouseRows, "status") },
  ],
  fields: [
    { key: "warehouseName", label: "Warehouse Name", type: "text" },
    { key: "warehouseCode", label: "Warehouse Code", type: "text" },
    {
      key: "warehouseType",
      label: "Warehouse Type",
      type: "select",
      options: ["Inward", "Storage", "Production"],
    },
    { key: "status", label: "Status", type: "select", options: uniqueOptions(warehouseRows, "status") },
    { key: "address", label: "Address", type: "text" },
    { key: "city", label: "City", type: "text" },
    { key: "pincode", label: "Pincode", type: "text" },
    { key: "state", label: "State", type: "select", options: uniqueOptions(warehouseRows, "state") },
    { key: "country", label: "Country", type: "select", options: uniqueOptions(warehouseRows, "country") },
    { key: "remark", label: "Remark", type: "text" },
  ],
  rows: warehouseRows,
};

export const currencyMasterDefinition: MasterDefinition = {
  slug: "currency-master",
  title: "Currency Master",
  gridColumns: 3,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "currencyName", label: "Currency Name" },
    { key: "remark", label: "Remark" },
    { key: "status", label: "Status" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    { key: "status", label: "Status", options: uniqueOptions(currencyRows, "status") },
    { key: "createdBy", label: "Created By", options: uniqueOptions(currencyRows, "createdBy") },
    { key: "currencyName", label: "Currency Name", options: uniqueOptions(currencyRows, "currencyName") },
  ],
  fields: [
    { key: "currencyName", label: "Currency Name", type: "text" },
    { key: "status", label: "Status", type: "select", options: uniqueOptions(currencyRows, "status") },
    { key: "remark", label: "Remark", type: "text" },
  ],
  rows: currencyRows,
};

export const unitMasterOptions = uniqueOptions(unitRows, "unitName");

export const transporterMasterOptions = uniqueOptions(
  transporterRows,
  "transporterName",
);

export const transporterTypeOptions = uniqueOptions(transporterRows, "type");

export const transporterAreaOfOperationOptions = uniqueOptions(
  transporterRows,
  "areaOfOperation",
);

export const transporterMasterDefinition: MasterDefinition = {
  slug: "transporter-master",
  title: "Transporter Master",
  gridColumns: 3,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "transporterName", label: "Transporter Name" },
    { key: "branchName", label: "Branch Name" },
    { key: "transporterId", label: "Transporter Id" },
    { key: "type", label: "Type" },
    { key: "areaOfOperation", label: "Area Of Operation" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    {
      key: "type",
      label: "Type",
      options: transporterTypeOptions,
    },
    {
      key: "areaOfOperation",
      label: "Area Of Operation",
      options: transporterAreaOfOperationOptions,
    },
  ],
  fields: [
    { key: "transporterName", label: "Transporter Name*", type: "text" },
    { key: "branchName", label: "Branch Name", type: "text" },
    { key: "transporterId", label: "Transporter Id", type: "text" },
    {
      key: "type",
      label: "Type*",
      type: "select",
      options: transporterTypeOptions,
    },
    {
      key: "areaOfOperation",
      label: "Area Of Operation*",
      type: "select",
      options: transporterAreaOfOperationOptions,
    },
  ],
  rows: transporterRows,
};

export const consumableCategoryOptions = uniqueOptions(
  consumablesRows,
  "category",
);

export const consumableMasterOptions = uniqueOptions(
  consumablesRows,
  "consumableName",
);

export const consumablesMasterDefinition: MasterDefinition = {
  slug: "consumables-master",
  title: "Consumables Master",
  gridColumns: 4,
  columns: [
    { key: "srNo", label: "Sr No" },
    { key: "consumableName", label: "Consumable Name" },
    { key: "category", label: "Category" },
    { key: "unitName", label: "Unit Name" },
    { key: "gst", label: "GST" },
    { key: "hsn", label: "HSN" },
    { key: "remark", label: "Remark" },
    { key: "createdBy", label: "Created By" },
    { key: "editedBy", label: "Edited By" },
    { key: "createdDate", label: "Created Date" },
    { key: "updatedDate", label: "Updated Date" },
  ],
  filters: [
    {
      key: "category",
      label: "Category",
      options: consumableCategoryOptions,
    },
    {
      key: "unitName",
      label: "Unit Name",
      options: unitMasterOptions,
    },
    {
      key: "gst",
      label: "GST",
      options: uniqueOptions(consumablesRows, "gst"),
    },
  ],
  fields: [
    { key: "consumableName", label: "Consumable Name", type: "text" },
    {
      key: "category",
      label: "Category",
      type: "select",
      options: consumableCategoryOptions,
    },
    {
      key: "unitName",
      label: "Unit Name",
      type: "select",
      options: unitMasterOptions,
    },
    {
      key: "gst",
      label: "GST",
      type: "select",
      options: uniqueOptions(gstRows, "gstPercentage"),
    },
    {
      key: "hsn",
      label: "HSN",
      type: "select",
      options: uniqueOptions(hsnRows, "hsnCode"),
    },
    { key: "remark", label: "Remark", type: "text" },
  ],
  rows: consumablesRows,
};
