import type { EnterpriseTableColumn } from "../../../components/data-display/EnterpriseDataTable";
import type { MasterFieldDefinition } from "../../masters/shared";
import {
  createInventoryRows,
  createInventoryViewFields,
  uniqueInventoryOptions,
} from "./inventoryUtils";
import type { InventoryDefinition, InventoryRecord } from "./types";

const asDate = (value: string) => new Date(value);

type RawVeneerRecord = InventoryRecord & {
  amount: string;
  approvalStatus: string;
  bundleNumber: string;
  currency: string;
  exchangeRate: string;
  inwardDate: Date;
  inwardSrNo: string;
  inwardType: string;
  invoiceNo: string;
  itemName: string;
  length: string;
  noOfLeavesSheets: string;
  noOfTotalHours: string;
  noOfWorkingHours: string;
  palletNo: string;
  remark: string;
  shift: string;
  srNo: string;
  subCategory: string;
  supplierCode: string;
  supplierItemName: string;
  supplierName: string;
  thickness: string;
  timberColor: string;
  totalSqm: string;
  veneerSrNo: string;
  width: string;
  workers: string;
};

type StockRecord = InventoryRecord & {
  amount: string;
  availableNoOfSheets: string;
  availableSqm: string;
  color: string;
  currency: string;
  exchangeRate: string;
  inwardDate: Date;
  inwardSrNo: string;
  inwardType: string;
  invoiceNo: string;
  itemName: string;
  itemSrNo: string;
  length: string;
  noOfTotalHours: string;
  noOfWorkingHours: string;
  palletNo: string;
  plywoodType: string;
  remark: string;
  shift: string;
  subCategory: string;
  supplierItemName: string;
  supplierName: string;
  thickness: string;
  totalNoOfSheets: string;
  totalSqm: string;
  width: string;
  workers: string;
};

type ConsumableRecord = InventoryRecord & {
  amount: string;
  availableQuantity: string;
  currency: string;
  exchangeRate: string;
  inwardDate: Date;
  inwardSrNo: string;
  inwardType: string;
  invoiceNo: string;
  itemName: string;
  itemSrNo: string;
  noOfTotalHours: string;
  noOfWorkingHours: string;
  quantity: string;
  remark: string;
  shift: string;
  subCategory: string;
  supplierItemName: string;
  supplierName: string;
  unitName: string;
  workers: string;
};

const rawVeneerColumns: ReadonlyArray<EnterpriseTableColumn<RawVeneerRecord>> = [
  { key: "srNo", label: "Sr No" },
  { key: "inwardSrNo", label: "Inward Sr No" },
  { key: "inwardType", label: "Inward Type" },
  { key: "inwardDate", label: "Inward Date" },
  { key: "invoiceNo", label: "Invoice No" },
  { key: "veneerSrNo", label: "Veneer Sr No" },
  { key: "supplierName", label: "Supplier Name" },
  { key: "supplierItemName", label: "Supplier Item Name" },
  { key: "supplierCode", label: "Supplier Code" },
  { key: "subCategory", label: "Sub Category" },
  { key: "itemName", label: "Item Name" },
  { key: "timberColor", label: "Timber Color" },
  { key: "bundleNumber", label: "Bundle Number" },
  { key: "palletNo", label: "Pallet No" },
  { key: "length", label: "Length" },
  { key: "width", label: "Width" },
  { key: "thickness", label: "Thickness" },
  { key: "noOfLeavesSheets", label: "No of Leaves/Sheets" },
  { key: "totalSqm", label: "Total SQM" },
  { key: "currency", label: "Currency" },
  { key: "amount", label: "Amount" },
  { key: "remark", label: "Remark" },
  { key: "approvalStatus", label: "Approval Status" },
];

const stockColumns: ReadonlyArray<EnterpriseTableColumn<StockRecord>> = [
  { key: "inwardSrNo", label: "Inward Sr No" },
  { key: "inwardType", label: "Inward Type" },
  { key: "inwardDate", label: "Inward Date" },
  { key: "invoiceNo", label: "Invoice No" },
  { key: "itemSrNo", label: "Item Sr No" },
  { key: "supplierName", label: "Supplier Name" },
  { key: "supplierItemName", label: "Supplier Item Name" },
  { key: "itemName", label: "Item Name" },
  { key: "subCategory", label: "Sub Category" },
  { key: "color", label: "Color" },
  { key: "plywoodType", label: "Plywood Type" },
  { key: "palletNo", label: "Pallet No" },
  { key: "length", label: "Length" },
  { key: "width", label: "Width" },
  { key: "thickness", label: "Thickness" },
  { key: "totalNoOfSheets", label: "Total No of Sheets" },
  { key: "availableNoOfSheets", label: "Available No of Sheets" },
  { key: "totalSqm", label: "Total SQM" },
  { key: "availableSqm", label: "Available SQM" },
  { key: "currency", label: "Currency" },
  { key: "amount", label: "Amount" },
  { key: "remark", label: "Remark" },
];

const consumableColumns: ReadonlyArray<
  EnterpriseTableColumn<ConsumableRecord>
> = [
  { key: "srNo", label: "Sr No" },
  { key: "inwardSrNo", label: "Inward Sr No" },
  { key: "inwardType", label: "Inward Type" },
  { key: "inwardDate", label: "Inward Date" },
  { key: "invoiceNo", label: "Invoice No" },
  { key: "itemSrNo", label: "Item Sr No" },
  { key: "supplierName", label: "Supplier Name" },
  { key: "supplierItemName", label: "Supplier Item Name" },
  { key: "itemName", label: "Consumable Name" },
  { key: "subCategory", label: "Category" },
  { key: "unitName", label: "Unit Name" },
  { key: "quantity", label: "Quantity" },
  { key: "availableQuantity", label: "Available Quantity" },
  { key: "currency", label: "Currency" },
  { key: "amount", label: "Amount" },
  { key: "remark", label: "Remark" },
];

function createInventoryFormFields(
  rows: readonly InventoryRecord[],
): ReadonlyArray<MasterFieldDefinition> {
  return [
    {
      key: "inwardType",
      label: "Inward Type",
      type: "select",
      options: uniqueInventoryOptions(rows, "inwardType"),
    },
    {
      key: "inwardDate",
      label: "Inward Date",
      type: "date",
    },
    {
      key: "supplierName",
      label: "Supplier Name",
      type: "select",
      options: uniqueInventoryOptions(rows, "supplierName"),
    },
    {
      key: "invoiceNo",
      label: "Invoice No",
      type: "text",
    },
    {
      key: "currency",
      label: "Currency",
      type: "select",
      options: uniqueInventoryOptions(rows, "currency"),
    },
    {
      key: "exchangeRate",
      label: "Exchange Rate",
      type: "text",
    },
    {
      key: "shift",
      label: "Shift",
      type: "select",
      options: uniqueInventoryOptions(rows, "shift"),
    },
    {
      key: "workers",
      label: "Workers",
      type: "text",
    },
    {
      key: "noOfWorkingHours",
      label: "No of Working Hours",
      type: "text",
    },
    {
      key: "noOfTotalHours",
      label: "No of Total Hours",
      type: "text",
    },
  ];
}

const inventoryEditSelectKeys = new Set([
  "approvalStatus",
  "color",
  "currency",
  "inwardType",
  "itemName",
  "itemSrNo",
  "plywoodType",
  "subCategory",
  "supplierCode",
  "supplierItemName",
  "supplierName",
  "timberColor",
  "unitName",
  "veneerSrNo",
]);

function createInventoryEditFields(
  columns: readonly { key: string; label: string }[],
  rows: readonly InventoryRecord[],
): ReadonlyArray<MasterFieldDefinition> {
  return columns.map<MasterFieldDefinition>((column) => {
    if (column.key === "inwardDate") {
      return {
        key: column.key,
        label: column.label,
        type: "date",
      };
    }

    if (inventoryEditSelectKeys.has(column.key)) {
      return {
        key: column.key,
        label: column.label,
        type: "select",
        options: uniqueInventoryOptions(rows, column.key),
      };
    }

    return {
      key: column.key,
      label: column.label,
      type: "text",
    };
  });
}

const rawVeneerRows = createInventoryRows<RawVeneerRecord>("raw-veneer", [
  {
    inwardSrNo: "INW-RV-2026-0001",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-02"),
    invoiceNo: "INV-PL-2401",
    veneerSrNo: "VNR-00041",
    supplierName: "Arihant Veneers LLP",
    supplierItemName: "Oak Quarter Cut Import Sheet",
    supplierCode: "SUP-ARH-014",
    subCategory: "Quarter Cut",
    itemName: "Oak Veneer",
    timberColor: "Natural Oak",
    bundleNumber: "BDL-OAK-2104",
    palletNo: "PAL-01-A",
    length: "2600 mm",
    width: "1220 mm",
    thickness: "0.60 mm",
    noOfLeavesSheets: "48",
    totalSqm: "152.340",
    currency: "INR",
    amount: "184,500.00",
    remark: "Moisture within approved inward range.",
    approvalStatus: "Approved",
    exchangeRate: "1.00",
    shift: "General",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0002",
    inwardType: "Import",
    inwardDate: asDate("2026-06-03"),
    invoiceNo: "INV-IT-7712",
    veneerSrNo: "VNR-00042",
    supplierName: "Euro Timber Exports",
    supplierItemName: "Walnut Crown Cut Export Pack",
    supplierCode: "SUP-EUR-009",
    subCategory: "Crown Cut",
    itemName: "Walnut Veneer",
    timberColor: "Dark Walnut",
    bundleNumber: "BDL-WAL-1820",
    palletNo: "PAL-02-B",
    length: "2500 mm",
    width: "1270 mm",
    thickness: "0.55 mm",
    noOfLeavesSheets: "52",
    totalSqm: "165.100",
    currency: "USD",
    amount: "3,820.00",
    remark: "Imported bundle tagged for premium grade allocation.",
    approvalStatus: "Pending Review",
    exchangeRate: "84.25",
    shift: "Morning",
    workers: "22",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0003",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-05"),
    invoiceNo: "INV-DM-1189",
    veneerSrNo: "VNR-00043",
    supplierName: "Shree Wood Panels",
    supplierItemName: "Teak Natural Decorative Sheet",
    supplierCode: "SUP-SWP-022",
    subCategory: "Natural",
    itemName: "Teak Veneer",
    timberColor: "Golden Brown",
    bundleNumber: "BDL-TEK-1942",
    palletNo: "PAL-03-C",
    length: "2400 mm",
    width: "1200 mm",
    thickness: "0.50 mm",
    noOfLeavesSheets: "44",
    totalSqm: "126.720",
    currency: "INR",
    amount: "132,400.00",
    remark: "Dispatch-ready after warehouse inspection.",
    approvalStatus: "Approved",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "16",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-RV-2026-0004",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-07"),
    invoiceNo: "INV-PL-2407",
    veneerSrNo: "VNR-00044",
    supplierName: "Prime Timber Sources",
    supplierItemName: "Ash Crown Cut Bundle",
    supplierCode: "SUP-PTS-031",
    subCategory: "Crown Cut",
    itemName: "Ash Veneer",
    timberColor: "Light Ash",
    bundleNumber: "BDL-ASH-1106",
    palletNo: "PAL-04-A",
    length: "2550 mm",
    width: "1240 mm",
    thickness: "0.58 mm",
    noOfLeavesSheets: "50",
    totalSqm: "158.100",
    currency: "INR",
    amount: "141,800.00",
    remark: "One pallet kept aside for remeasurement.",
    approvalStatus: "On Hold",
    exchangeRate: "1.00",
    shift: "General",
    workers: "19",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0005",
    inwardType: "Import",
    inwardDate: asDate("2026-06-09"),
    invoiceNo: "INV-IT-7720",
    veneerSrNo: "VNR-00045",
    supplierName: "Nordic Veneer House",
    supplierItemName: "Oak Rift Cut Architectural Sheet",
    supplierCode: "SUP-NVH-011",
    subCategory: "Rift Cut",
    itemName: "Oak Veneer",
    timberColor: "Smoked Natural",
    bundleNumber: "BDL-OAK-2198",
    palletNo: "PAL-05-D",
    length: "2800 mm",
    width: "1250 mm",
    thickness: "0.65 mm",
    noOfLeavesSheets: "40",
    totalSqm: "140.000",
    currency: "EUR",
    amount: "4,650.00",
    remark: "Long-sheet inward suited for export furniture program.",
    approvalStatus: "Approved",
    exchangeRate: "91.10",
    shift: "Morning",
    workers: "20",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-RV-2026-0006",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-11"),
    invoiceNo: "INV-DM-1198",
    veneerSrNo: "VNR-00046",
    supplierName: "Mewar Decorative Woods",
    supplierItemName: "Walnut Quarter Cut Standard Pack",
    supplierCode: "SUP-MDW-019",
    subCategory: "Quarter Cut",
    itemName: "Walnut Veneer",
    timberColor: "Rich Walnut",
    bundleNumber: "BDL-WAL-1904",
    palletNo: "PAL-06-B",
    length: "2500 mm",
    width: "1220 mm",
    thickness: "0.62 mm",
    noOfLeavesSheets: "46",
    totalSqm: "140.300",
    currency: "INR",
    amount: "168,900.00",
    remark: "Supplier label matched inward purchase order.",
    approvalStatus: "Approved",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "17",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-RV-2026-0007",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-13"),
    invoiceNo: "INV-PL-2415",
    veneerSrNo: "VNR-00047",
    supplierName: "Heritage Panel Works",
    supplierItemName: "Teak Crown Cut Interior Pack",
    supplierCode: "SUP-HPW-027",
    subCategory: "Crown Cut",
    itemName: "Teak Veneer",
    timberColor: "Honey Teak",
    bundleNumber: "BDL-TEK-1995",
    palletNo: "PAL-07-C",
    length: "2450 mm",
    width: "1210 mm",
    thickness: "0.52 mm",
    noOfLeavesSheets: "54",
    totalSqm: "160.080",
    currency: "INR",
    amount: "149,750.00",
    remark: "Approved with note for crown cut grain variation.",
    approvalStatus: "Approved",
    exchangeRate: "1.00",
    shift: "General",
    workers: "21",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0008",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-16"),
    invoiceNo: "INV-DM-1210",
    veneerSrNo: "VNR-00048",
    supplierName: "City Timber Traders",
    supplierItemName: "Ash Natural Light Bundle",
    supplierCode: "SUP-CTT-018",
    subCategory: "Natural",
    itemName: "Ash Veneer",
    timberColor: "Soft Grey",
    bundleNumber: "BDL-ASH-1164",
    palletNo: "PAL-08-A",
    length: "2350 mm",
    width: "1180 mm",
    thickness: "0.48 mm",
    noOfLeavesSheets: "56",
    totalSqm: "155.290",
    currency: "INR",
    amount: "126,300.00",
    remark: "Pending approval after moisture retest.",
    approvalStatus: "Pending Review",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "15",
    noOfWorkingHours: "7.0",
    noOfTotalHours: "8.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0009",
    inwardType: "Import",
    inwardDate: asDate("2026-06-18"),
    invoiceNo: "INV-IT-7744",
    veneerSrNo: "VNR-00049",
    supplierName: "Baltic Timber Supply",
    supplierItemName: "Oak Crown Cut Premium Set",
    supplierCode: "SUP-BTS-007",
    subCategory: "Crown Cut",
    itemName: "Oak Veneer",
    timberColor: "Warm Natural",
    bundleNumber: "BDL-OAK-2237",
    palletNo: "PAL-09-D",
    length: "2700 mm",
    width: "1250 mm",
    thickness: "0.64 mm",
    noOfLeavesSheets: "42",
    totalSqm: "141.750",
    currency: "USD",
    amount: "3,960.00",
    remark: "QC requested closer veneer serial verification.",
    approvalStatus: "Pending Review",
    exchangeRate: "84.40",
    shift: "General",
    workers: "23",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0010",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-20"),
    invoiceNo: "INV-PL-2421",
    veneerSrNo: "VNR-00050",
    supplierName: "Royal Laminates India",
    supplierItemName: "Walnut Natural Feature Bundle",
    supplierCode: "SUP-RLI-029",
    subCategory: "Natural",
    itemName: "Walnut Veneer",
    timberColor: "Classic Walnut",
    bundleNumber: "BDL-WAL-1968",
    palletNo: "PAL-10-B",
    length: "2480 mm",
    width: "1230 mm",
    thickness: "0.60 mm",
    noOfLeavesSheets: "49",
    totalSqm: "149.450",
    currency: "INR",
    amount: "171,200.00",
    remark: "Released for production issue to premium line.",
    approvalStatus: "Approved",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
]);

const veneerBlocksRows = createInventoryRows<StockRecord>("veneer-blocks", [
  {
    inwardSrNo: "INW-VB-2026-0001",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-02"),
    invoiceNo: "VB-2401",
    itemSrNo: "ITM-VB-001",
    supplierName: "Arihant Veneers LLP",
    supplierItemName: "Oak Core Block Pack",
    itemName: "Oak Veneer Block",
    subCategory: "Quarter Cut",
    color: "Natural Oak",
    plywoodType: "Decorative",
    palletNo: "VB-PAL-01",
    length: "2550 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "120",
    availableNoOfSheets: "92",
    totalSqm: "310.500",
    availableSqm: "237.820",
    currency: "INR",
    amount: "284,500.00",
    remark: "Issued partially to pressing.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0002",
    inwardType: "Import",
    inwardDate: asDate("2026-06-04"),
    invoiceNo: "VB-7712",
    itemSrNo: "ITM-VB-002",
    supplierName: "Euro Timber Exports",
    supplierItemName: "Walnut Architectural Block",
    itemName: "Walnut Veneer Block",
    subCategory: "Crown Cut",
    color: "Dark Walnut",
    plywoodType: "Architectural",
    palletNo: "VB-PAL-02",
    length: "2700 mm",
    width: "1250 mm",
    thickness: "19 mm",
    totalNoOfSheets: "96",
    availableNoOfSheets: "81",
    totalSqm: "324.000",
    availableSqm: "273.370",
    currency: "USD",
    amount: "5,920.00",
    remark: "Reserved for premium furniture line.",
    exchangeRate: "84.25",
    shift: "Morning",
    workers: "22",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0003",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-06"),
    invoiceNo: "VB-1189",
    itemSrNo: "ITM-VB-003",
    supplierName: "Shree Wood Panels",
    supplierItemName: "Teak Natural Stock Block",
    itemName: "Teak Veneer Block",
    subCategory: "Natural",
    color: "Golden Teak",
    plywoodType: "Commercial",
    palletNo: "VB-PAL-03",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "16 mm",
    totalNoOfSheets: "140",
    availableNoOfSheets: "140",
    totalSqm: "417.000",
    availableSqm: "417.000",
    currency: "INR",
    amount: "318,600.00",
    remark: "Fresh inward pending line allocation.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "16",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-VB-2026-0004",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-08"),
    invoiceNo: "VB-2407",
    itemSrNo: "ITM-VB-004",
    supplierName: "Prime Timber Sources",
    supplierItemName: "Ash Core Assembly Block",
    itemName: "Ash Veneer Block",
    subCategory: "Crown Cut",
    color: "Soft Ash",
    plywoodType: "Decorative",
    palletNo: "VB-PAL-04",
    length: "2500 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "110",
    availableNoOfSheets: "78",
    totalSqm: "335.500",
    availableSqm: "237.900",
    currency: "INR",
    amount: "276,400.00",
    remark: "Shortfall due to issued samples.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "19",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0005",
    inwardType: "Import",
    inwardDate: asDate("2026-06-10"),
    invoiceNo: "VB-7720",
    itemSrNo: "ITM-VB-005",
    supplierName: "Nordic Veneer House",
    supplierItemName: "Oak Rift Cut Structural Block",
    itemName: "Oak Veneer Block",
    subCategory: "Rift Cut",
    color: "Smoked Natural",
    plywoodType: "Architectural",
    palletNo: "VB-PAL-05",
    length: "2800 mm",
    width: "1250 mm",
    thickness: "20 mm",
    totalNoOfSheets: "88",
    availableNoOfSheets: "63",
    totalSqm: "308.000",
    availableSqm: "220.500",
    currency: "EUR",
    amount: "6,250.00",
    remark: "Held for export-panel planning.",
    exchangeRate: "91.10",
    shift: "Morning",
    workers: "20",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-VB-2026-0006",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-12"),
    invoiceNo: "VB-1198",
    itemSrNo: "ITM-VB-006",
    supplierName: "Mewar Decorative Woods",
    supplierItemName: "Walnut Standard Block Pack",
    itemName: "Walnut Veneer Block",
    subCategory: "Quarter Cut",
    color: "Rich Walnut",
    plywoodType: "Decorative",
    palletNo: "VB-PAL-06",
    length: "2480 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "102",
    availableNoOfSheets: "84",
    totalSqm: "303.400",
    availableSqm: "249.270",
    currency: "INR",
    amount: "295,900.00",
    remark: "Supplier label matched inward purchase order.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "17",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-VB-2026-0007",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-14"),
    invoiceNo: "VB-2415",
    itemSrNo: "ITM-VB-007",
    supplierName: "Heritage Panel Works",
    supplierItemName: "Teak Interior Block Bundle",
    itemName: "Teak Veneer Block",
    subCategory: "Crown Cut",
    color: "Honey Teak",
    plywoodType: "Commercial",
    palletNo: "VB-PAL-07",
    length: "2450 mm",
    width: "1210 mm",
    thickness: "17 mm",
    totalNoOfSheets: "126",
    availableNoOfSheets: "101",
    totalSqm: "372.600",
    availableSqm: "298.700",
    currency: "INR",
    amount: "264,750.00",
    remark: "Allocated partially to factory cutting line.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "21",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0008",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-16"),
    invoiceNo: "VB-1210",
    itemSrNo: "ITM-VB-008",
    supplierName: "City Timber Traders",
    supplierItemName: "Ash Light Production Block",
    itemName: "Ash Veneer Block",
    subCategory: "Natural",
    color: "Soft Grey",
    plywoodType: "Commercial",
    palletNo: "VB-PAL-08",
    length: "2350 mm",
    width: "1180 mm",
    thickness: "16 mm",
    totalNoOfSheets: "132",
    availableNoOfSheets: "132",
    totalSqm: "367.200",
    availableSqm: "367.200",
    currency: "INR",
    amount: "236,300.00",
    remark: "Awaiting QC tagging for warehouse transfer.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "15",
    noOfWorkingHours: "7.0",
    noOfTotalHours: "8.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0009",
    inwardType: "Import",
    inwardDate: asDate("2026-06-18"),
    invoiceNo: "VB-7744",
    itemSrNo: "ITM-VB-009",
    supplierName: "Baltic Timber Supply",
    supplierItemName: "Oak Premium Block Set",
    itemName: "Oak Veneer Block",
    subCategory: "Crown Cut",
    color: "Warm Natural",
    plywoodType: "Architectural",
    palletNo: "VB-PAL-09",
    length: "2700 mm",
    width: "1250 mm",
    thickness: "19 mm",
    totalNoOfSheets: "94",
    availableNoOfSheets: "68",
    totalSqm: "317.300",
    availableSqm: "229.480",
    currency: "USD",
    amount: "5,480.00",
    remark: "QC requested closer veneer serial verification.",
    exchangeRate: "84.40",
    shift: "General",
    workers: "23",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0010",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-20"),
    invoiceNo: "VB-2421",
    itemSrNo: "ITM-VB-010",
    supplierName: "Royal Laminates India",
    supplierItemName: "Walnut Feature Block Bundle",
    itemName: "Walnut Veneer Block",
    subCategory: "Natural",
    color: "Classic Walnut",
    plywoodType: "Decorative",
    palletNo: "VB-PAL-10",
    length: "2480 mm",
    width: "1230 mm",
    thickness: "18 mm",
    totalNoOfSheets: "108",
    availableNoOfSheets: "86",
    totalSqm: "314.800",
    availableSqm: "250.760",
    currency: "INR",
    amount: "301,200.00",
    remark: "Released for premium line issue.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
]);

const plywoodRows = createInventoryRows<StockRecord>("plywood", [
  {
    inwardSrNo: "INW-PL-2026-0001",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-03"),
    invoiceNo: "PLY-2401",
    itemSrNo: "ITM-PLY-001",
    supplierName: "Panel Craft India",
    supplierItemName: "BWP Decorative Plywood Pack",
    itemName: "BWP Plywood",
    subCategory: "Premium",
    color: "Warm Birch",
    plywoodType: "BWP",
    palletNo: "PLY-PAL-01",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "180",
    availableNoOfSheets: "154",
    totalSqm: "535.680",
    availableSqm: "458.970",
    currency: "INR",
    amount: "428,600.00",
    remark: "Primary inward for modular panel jobs.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-PL-2026-0002",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-05"),
    invoiceNo: "PLY-2405",
    itemSrNo: "ITM-PLY-002",
    supplierName: "Western Ply Boards",
    supplierItemName: "Commercial Plywood Standard Pack",
    itemName: "Commercial Plywood",
    subCategory: "Standard",
    color: "Natural Beige",
    plywoodType: "Commercial",
    palletNo: "PLY-PAL-02",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "12 mm",
    totalNoOfSheets: "220",
    availableNoOfSheets: "194",
    totalSqm: "654.940",
    availableSqm: "577.600",
    currency: "INR",
    amount: "352,400.00",
    remark: "Issued partially to packing mockup jobs.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "20",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-PL-2026-0003",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-07"),
    invoiceNo: "PLY-2407",
    itemSrNo: "ITM-PLY-003",
    supplierName: "Timbercore Panels",
    supplierItemName: "Marine Grade Panel Bundle",
    itemName: "Marine Plywood",
    subCategory: "Premium",
    color: "Rich Brown",
    plywoodType: "Marine",
    palletNo: "PLY-PAL-03",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "140",
    availableNoOfSheets: "132",
    totalSqm: "416.640",
    availableSqm: "392.840",
    currency: "INR",
    amount: "389,800.00",
    remark: "Reserved for wet-area projects.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "17",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-PL-2026-0004",
    inwardType: "Import",
    inwardDate: asDate("2026-06-09"),
    invoiceNo: "PLY-7719",
    itemSrNo: "ITM-PLY-004",
    supplierName: "Scandic Wood Surfaces",
    supplierItemName: "Architectural Birch Panel Set",
    itemName: "Birch Plywood",
    subCategory: "Architectural",
    color: "Pale Birch",
    plywoodType: "Architectural",
    palletNo: "PLY-PAL-04",
    length: "2500 mm",
    width: "1250 mm",
    thickness: "18 mm",
    totalNoOfSheets: "116",
    availableNoOfSheets: "95",
    totalSqm: "362.500",
    availableSqm: "296.870",
    currency: "EUR",
    amount: "6,780.00",
    remark: "Imported lot for export fixtures.",
    exchangeRate: "91.10",
    shift: "Morning",
    workers: "22",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-PL-2026-0005",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-11"),
    invoiceNo: "PLY-2411",
    itemSrNo: "ITM-PLY-005",
    supplierName: "Heritage Panel Works",
    supplierItemName: "Flexible MDF-Backed Plywood",
    itemName: "Flexible Plywood",
    subCategory: "Specialty",
    color: "Soft Walnut",
    plywoodType: "Flexible",
    palletNo: "PLY-PAL-05",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "6 mm",
    totalNoOfSheets: "260",
    availableNoOfSheets: "218",
    totalSqm: "773.920",
    availableSqm: "648.290",
    currency: "INR",
    amount: "314,900.00",
    remark: "Used for curved cladding mockups.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "19",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-PL-2026-0006",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-13"),
    invoiceNo: "PLY-2413",
    itemSrNo: "ITM-PLY-006",
    supplierName: "Royal Laminates India",
    supplierItemName: "Calibrated Ply Sheet Pack",
    itemName: "Calibrated Plywood",
    subCategory: "Precision",
    color: "Warm Sand",
    plywoodType: "Calibrated",
    palletNo: "PLY-PAL-06",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "16 mm",
    totalNoOfSheets: "168",
    availableNoOfSheets: "152",
    totalSqm: "500.650",
    availableSqm: "453.010",
    currency: "INR",
    amount: "366,200.00",
    remark: "Factory-preferred inward for CNC jobs.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-PL-2026-0007",
    inwardType: "Import",
    inwardDate: asDate("2026-06-15"),
    invoiceNo: "PLY-7726",
    itemSrNo: "ITM-PLY-007",
    supplierName: "Nordic Veneer House",
    supplierItemName: "Oak Faced Panel Bundle",
    itemName: "Oak Faced Plywood",
    subCategory: "Architectural",
    color: "Natural Oak",
    plywoodType: "Faced",
    palletNo: "PLY-PAL-07",
    length: "2500 mm",
    width: "1250 mm",
    thickness: "18 mm",
    totalNoOfSheets: "124",
    availableNoOfSheets: "110",
    totalSqm: "387.500",
    availableSqm: "343.750",
    currency: "USD",
    amount: "6,120.00",
    remark: "Held for architect-specified facade work.",
    exchangeRate: "84.50",
    shift: "Morning",
    workers: "21",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-PL-2026-0008",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-17"),
    invoiceNo: "PLY-2417",
    itemSrNo: "ITM-PLY-008",
    supplierName: "City Timber Traders",
    supplierItemName: "Economy Ply Stock Lot",
    itemName: "Economy Plywood",
    subCategory: "Standard",
    color: "Neutral Brown",
    plywoodType: "Commercial",
    palletNo: "PLY-PAL-08",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "9 mm",
    totalNoOfSheets: "240",
    availableNoOfSheets: "210",
    totalSqm: "714.720",
    availableSqm: "625.380",
    currency: "INR",
    amount: "286,900.00",
    remark: "Allocated for secondary furniture runs.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "16",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-PL-2026-0009",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-19"),
    invoiceNo: "PLY-2419",
    itemSrNo: "ITM-PLY-009",
    supplierName: "Panel Craft India",
    supplierItemName: "MR Grade Panel Refill",
    itemName: "MR Plywood",
    subCategory: "Utility",
    color: "Warm Beige",
    plywoodType: "MR",
    palletNo: "PLY-PAL-09",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "12 mm",
    totalNoOfSheets: "210",
    availableNoOfSheets: "188",
    totalSqm: "625.240",
    availableSqm: "559.760",
    currency: "INR",
    amount: "301,500.00",
    remark: "Replenishment for factory day shift.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "20",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-PL-2026-0010",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-21"),
    invoiceNo: "PLY-2421",
    itemSrNo: "ITM-PLY-010",
    supplierName: "Western Ply Boards",
    supplierItemName: "Fire Retardant Panel Stack",
    itemName: "Fire Retardant Plywood",
    subCategory: "Specialty",
    color: "Deep Brown",
    plywoodType: "FR",
    palletNo: "PLY-PAL-10",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "128",
    availableNoOfSheets: "119",
    totalSqm: "381.270",
    availableSqm: "354.470",
    currency: "INR",
    amount: "418,900.00",
    remark: "Reserved for hospitality interior fit-outs.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
]);

const mdfRows = createInventoryRows<StockRecord>("mdf", [
  {
    inwardSrNo: "INW-MDF-2026-0001",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-03"),
    invoiceNo: "MDF-2401",
    itemSrNo: "ITM-MDF-001",
    supplierName: "Urban Board Industries",
    supplierItemName: "Standard MDF Board Pack",
    itemName: "Standard MDF",
    subCategory: "Interior",
    color: "Natural Brown",
    plywoodType: "Plain",
    palletNo: "MDF-PAL-01",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "200",
    availableNoOfSheets: "172",
    totalSqm: "595.360",
    availableSqm: "511.990",
    currency: "INR",
    amount: "248,600.00",
    remark: "Daily inward for panel processing.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-MDF-2026-0002",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-05"),
    invoiceNo: "MDF-2405",
    itemSrNo: "ITM-MDF-002",
    supplierName: "Boardline Panels",
    supplierItemName: "Prelam MDF Bundle",
    itemName: "Prelam MDF",
    subCategory: "Decorative",
    color: "Maple Beige",
    plywoodType: "Prelam",
    palletNo: "MDF-PAL-02",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "17 mm",
    totalNoOfSheets: "168",
    availableNoOfSheets: "151",
    totalSqm: "500.100",
    availableSqm: "449.480",
    currency: "INR",
    amount: "292,400.00",
    remark: "Used for wardrobe shutter programs.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "19",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-MDF-2026-0003",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-07"),
    invoiceNo: "MDF-2407",
    itemSrNo: "ITM-MDF-003",
    supplierName: "Decorcore Sheets",
    supplierItemName: "High Density MDF Stack",
    itemName: "High Density MDF",
    subCategory: "Structural",
    color: "Smoke Brown",
    plywoodType: "HDF",
    palletNo: "MDF-PAL-03",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "156",
    availableNoOfSheets: "138",
    totalSqm: "464.380",
    availableSqm: "410.790",
    currency: "INR",
    amount: "318,900.00",
    remark: "Factory-preferred for CNC routing.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "17",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-MDF-2026-0004",
    inwardType: "Import",
    inwardDate: asDate("2026-06-09"),
    invoiceNo: "MDF-7719",
    itemSrNo: "ITM-MDF-004",
    supplierName: "Scandic Wood Surfaces",
    supplierItemName: "Moisture Resistant MDF Set",
    itemName: "MR MDF",
    subCategory: "Specialty",
    color: "Warm Grey",
    plywoodType: "MR",
    palletNo: "MDF-PAL-04",
    length: "2500 mm",
    width: "1250 mm",
    thickness: "18 mm",
    totalNoOfSheets: "120",
    availableNoOfSheets: "102",
    totalSqm: "375.000",
    availableSqm: "318.750",
    currency: "EUR",
    amount: "5,620.00",
    remark: "Reserved for washroom vanity programs.",
    exchangeRate: "91.10",
    shift: "Morning",
    workers: "21",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-MDF-2026-0005",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-11"),
    invoiceNo: "MDF-2411",
    itemSrNo: "ITM-MDF-005",
    supplierName: "Heritage Panel Works",
    supplierItemName: "Flexi MDF Rollout Bundle",
    itemName: "Flexible MDF",
    subCategory: "Specialty",
    color: "Coffee Brown",
    plywoodType: "Flexible",
    palletNo: "MDF-PAL-05",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "6 mm",
    totalNoOfSheets: "240",
    availableNoOfSheets: "210",
    totalSqm: "714.720",
    availableSqm: "625.380",
    currency: "INR",
    amount: "274,900.00",
    remark: "Used for curved decorative panels.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "19",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-MDF-2026-0006",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-13"),
    invoiceNo: "MDF-2413",
    itemSrNo: "ITM-MDF-006",
    supplierName: "Royal Laminates India",
    supplierItemName: "Exterior Grade MDF Pack",
    itemName: "Exterior MDF",
    subCategory: "Exterior",
    color: "Deep Walnut",
    plywoodType: "Exterior",
    palletNo: "MDF-PAL-06",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "132",
    availableNoOfSheets: "118",
    totalSqm: "392.910",
    availableSqm: "351.240",
    currency: "INR",
    amount: "332,600.00",
    remark: "Allocated for facade backing panels.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-MDF-2026-0007",
    inwardType: "Import",
    inwardDate: asDate("2026-06-15"),
    invoiceNo: "MDF-7726",
    itemSrNo: "ITM-MDF-007",
    supplierName: "Nordic Veneer House",
    supplierItemName: "Oak Tone Veneered MDF Bundle",
    itemName: "Veneered MDF",
    subCategory: "Architectural",
    color: "Natural Oak",
    plywoodType: "Veneered",
    palletNo: "MDF-PAL-07",
    length: "2500 mm",
    width: "1250 mm",
    thickness: "18 mm",
    totalNoOfSheets: "118",
    availableNoOfSheets: "99",
    totalSqm: "368.750",
    availableSqm: "309.790",
    currency: "USD",
    amount: "5,980.00",
    remark: "Held for premium lobby wall cladding.",
    exchangeRate: "84.50",
    shift: "Morning",
    workers: "22",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-MDF-2026-0008",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-17"),
    invoiceNo: "MDF-2417",
    itemSrNo: "ITM-MDF-008",
    supplierName: "City Timber Traders",
    supplierItemName: "Economy MDF Stock Lot",
    itemName: "Economy MDF",
    subCategory: "Utility",
    color: "Neutral Grey",
    plywoodType: "Plain",
    palletNo: "MDF-PAL-08",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "9 mm",
    totalNoOfSheets: "280",
    availableNoOfSheets: "248",
    totalSqm: "833.740",
    availableSqm: "738.750",
    currency: "INR",
    amount: "256,900.00",
    remark: "Allocated for secondary carcass work.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "16",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-MDF-2026-0009",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-19"),
    invoiceNo: "MDF-2419",
    itemSrNo: "ITM-MDF-009",
    supplierName: "Urban Board Industries",
    supplierItemName: "Fire Retardant MDF Panel Pack",
    itemName: "FR MDF",
    subCategory: "Specialty",
    color: "Muted Brown",
    plywoodType: "FR",
    palletNo: "MDF-PAL-09",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "16 mm",
    totalNoOfSheets: "154",
    availableNoOfSheets: "143",
    totalSqm: "458.340",
    availableSqm: "425.600",
    currency: "INR",
    amount: "344,800.00",
    remark: "Reserved for hospitality corridor package.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "20",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-MDF-2026-0010",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-21"),
    invoiceNo: "MDF-2421",
    itemSrNo: "ITM-MDF-010",
    supplierName: "Boardline Panels",
    supplierItemName: "Moisture Shield MDF Stack",
    itemName: "Moisture Shield MDF",
    subCategory: "Interior",
    color: "Satin Beige",
    plywoodType: "MR",
    palletNo: "MDF-PAL-10",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "146",
    availableNoOfSheets: "128",
    totalSqm: "434.890",
    availableSqm: "381.830",
    currency: "INR",
    amount: "318,400.00",
    remark: "To be issued against kitchen shutter schedule.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
]);

const consumablesRows = createInventoryRows<ConsumableRecord>("consumables", [
  {
    inwardSrNo: "INW-CON-2026-0001",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-04"),
    invoiceNo: "CON-2404",
    itemSrNo: "CON-001",
    supplierName: "Arihant Veneers LLP",
    supplierItemName: "Fevicol SH Resin Drum",
    itemName: "Fevicol SH Resin",
    subCategory: "Adhesive",
    unitName: "Kilogram",
    quantity: "450",
    availableQuantity: "320",
    currency: "INR",
    amount: "86,400.00",
    remark: "Issued partially to pressing and grouping lines.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "12",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-CON-2026-0002",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-07"),
    invoiceNo: "CON-2407",
    itemSrNo: "CON-002",
    supplierName: "Heritage Panel Works",
    supplierItemName: "Melamine Hardener Canister",
    itemName: "Melamine Glue Hardener",
    subCategory: "Chemical",
    unitName: "Litre",
    quantity: "180",
    availableQuantity: "122",
    currency: "INR",
    amount: "54,900.00",
    remark: "Standard hardener stock for hot press adhesive preparation.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "10",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-CON-2026-0003",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-10"),
    invoiceNo: "CON-2410",
    itemSrNo: "CON-003",
    supplierName: "City Timber Traders",
    supplierItemName: "Edge Protector Roll",
    itemName: "Edge Protector Roll",
    subCategory: "Packaging",
    unitName: "Roll",
    quantity: "300",
    availableQuantity: "248",
    currency: "INR",
    amount: "39,750.00",
    remark: "Reserved for finished veneer and plywood dispatch packing.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "8",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-CON-2026-0004",
    inwardType: "Domestic",
    inwardDate: asDate("2026-06-14"),
    invoiceNo: "CON-2414",
    itemSrNo: "CON-004",
    supplierName: "Royal Laminates India",
    supplierItemName: "Sanding Belt 120 Grit",
    itemName: "Sanding Belt 120 Grit",
    subCategory: "Hardware",
    unitName: "Piece",
    quantity: "520",
    availableQuantity: "406",
    currency: "INR",
    amount: "28,600.00",
    remark: "Consumed across finishing and sample sheet runs.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "14",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-CON-2026-0005",
    inwardType: "Import",
    inwardDate: asDate("2026-06-18"),
    invoiceNo: "CON-7722",
    itemSrNo: "CON-005",
    supplierName: "Scandic Wood Surfaces",
    supplierItemName: "Press Release Film Stack",
    itemName: "Press Release Film",
    subCategory: "Packaging",
    unitName: "Roll",
    quantity: "140",
    availableQuantity: "104",
    currency: "USD",
    amount: "1,280.00",
    remark: "Speciality packing material for export and OEM orders.",
    exchangeRate: "84.30",
    shift: "Morning",
    workers: "9",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-CON-2026-0006",
    inwardType: "Purchase",
    inwardDate: asDate("2026-06-21"),
    invoiceNo: "CON-2421",
    itemSrNo: "CON-006",
    supplierName: "Prime Timber Sources",
    supplierItemName: "PU Adhesive Cartridge",
    itemName: "PU Adhesive Cartridge",
    subCategory: "Adhesive",
    unitName: "Piece",
    quantity: "260",
    availableQuantity: "198",
    currency: "INR",
    amount: "61,100.00",
    remark: "Reserved for decorative assembly and marquetry works.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "11",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
]);

export const rawVeneerDefinition: InventoryDefinition<RawVeneerRecord> = {
  slug: "raw-veneer",
  title: "Raw Veneer",
  listColumns: rawVeneerColumns,
  editFields: createInventoryEditFields(rawVeneerColumns, rawVeneerRows),
  formFields: createInventoryFormFields(rawVeneerRows),
  viewFields: createInventoryViewFields(rawVeneerColumns),
  rows: rawVeneerRows,
  initialSort: { key: "inwardDate", direction: "desc" },
};

export const veneerBlocksDefinition: InventoryDefinition<StockRecord> = {
  slug: "veneer-blocks",
  title: "Veneer Blocks",
  listColumns: stockColumns,
  editFields: createInventoryEditFields(stockColumns, veneerBlocksRows),
  formFields: createInventoryFormFields(veneerBlocksRows),
  viewFields: createInventoryViewFields(stockColumns),
  rows: veneerBlocksRows,
  initialSort: { key: "inwardDate", direction: "desc" },
};

export const plywoodDefinition: InventoryDefinition<StockRecord> = {
  slug: "plywood",
  title: "Plywood",
  listColumns: stockColumns,
  editFields: createInventoryEditFields(stockColumns, plywoodRows),
  formFields: createInventoryFormFields(plywoodRows),
  viewFields: createInventoryViewFields(stockColumns),
  rows: plywoodRows,
  initialSort: { key: "inwardDate", direction: "desc" },
};

export const mdfDefinition: InventoryDefinition<StockRecord> = {
  slug: "mdf",
  title: "MDF",
  listColumns: stockColumns,
  editFields: createInventoryEditFields(stockColumns, mdfRows),
  formFields: createInventoryFormFields(mdfRows),
  viewFields: createInventoryViewFields(stockColumns),
  rows: mdfRows,
  initialSort: { key: "inwardDate", direction: "desc" },
};

export const consumablesDefinition: InventoryDefinition<ConsumableRecord> = {
  slug: "consumables",
  title: "Consumables",
  listColumns: consumableColumns,
  editFields: createInventoryEditFields(consumableColumns, consumablesRows),
  formFields: createInventoryFormFields(consumablesRows),
  viewFields: createInventoryViewFields(consumableColumns),
  rows: consumablesRows,
  initialSort: { key: "inwardDate", direction: "desc" },
};
